#-------------------------------
# General Site Settings

title: Teckmon{STER}
description: Science // Technology // Engineering // Research
email: teckmonsiaw@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '/#about-me'}
- {name: Projects, url: '/#work'}
#- {name: Blog, url: '/post'}
- {name: Contact, url: '/#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

#seo:
#  description: 'Provide a description for your website to make it visible to search engines.'
#  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
#  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Welcome to [Teckmon{STER}](http://teckmonster.com){:target="_blank"}!** 


  This is my portfolio where I am sharing some interested projects I am currently working on at my leisure. 
  {STER} refers to SCIENCE, TECHNOLOGY, ENGINEERING, and RESEARCH. 


  Data analytics is inherently interdisciplinary with a vast array of applications. Modern technology generates enormous 
  amounts of data, yet the ability to analyze and apply this data well and with relevance is still lacking. There are a
  lot of topics that I am passionate and curious to learn more about such as healthcare, fitness, nutrition, national geographics, 
  logistics, and travel.  


  I hope that by working on these projects and it will prepare me with the skills necessary to be ready fields heavily involved 
  with data analytics and machine learning and bring the design into real world use.


  Since graduating from Georgia Tech in 2013, I have worked in both an academic endowment investment setting and in the corporate 
  insurance industry. In these roles, I have built an extensive understanding of data gathering, processing, automation, 
  and database development. With this background, I hope to expand my ability to analyze and apply data.
  

  Beside data analytics, I weightlift, practice yoga, meditate, back country backpack, and build websites. 


skills:
- {name: Georgia Institute of Technology with a degree in IE, value: '10'}
- {name: Registered Yoga Teacher RYT 200 through Yoga Alliance, value: '10'}
- {name: Retrieve data with SQL across multiple database environments, value: '10'}
- {name: Data Analytics with Python and Tableau, value: '9'}
- {name: Machine Learning, value: '2'}

# [Resume](https://drive.google.com/file/d/1GLLzwb8AVtWQ4on6NHE_jqsbMXMB5uxv/view?usp=sharing){:target="_blank"}

 
#- {name: Certified Sports Performance Coach through USA Weightlifting, value: '10'}
#- {name: Nutrition, value: '9'}

#-------------------------------
# Work Section

projects:
- {name: Weightlifting, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: Yoga, folder: 'proj-2', file: 'work/proj-2.html'}
#- {name: Nutrition, folder: 'proj-3', file: 'work/proj-3.html'}
#- {name: Backpacking, folder: 'proj-4', file: 'work/proj-4.html'}
# - {name: Fresh It Up, folder: 'proj-5', file: 'work/proj-5.html'}
# - {name: Timeline Page, folder: 'proj-6', file: 'work/proj-6.html'}
# - {name: Weather Dashboard, folder: 'proj-7', file: 'work/proj-7.html'}
# - {name: Stripes & Co, folder: 'proj-8', file: 'work/proj-8.html'}



#-------------------------------
# Testimonials Section

clients:
- {avatar: 'face-aaroni.jpg',
  name: 'Mark Rippetoe',
  title: 'Basic Barbell Training',
  quote: '<p><strong>Our primary concern is that doing it lifting wrong is also inefficient,</strong> so we will do it right because that ultimately allows us to lift more weight and get stronger, and safety will be a welcome side effect.</p>',
  logo:  'logo1.png'}
- {avatar: 'face-jackiesaik.jpg',
  name: 'Morghan King',
  title: '48kg U.S. Olympics Weightlifter',
  quote: '<p><strong>Strength comes from being physically and mentally strong.</strong> You can be an incredible athlete who is as strong as an ox, but if you are not mentally strong, you’re going to have a tough time making it to the top in any sport.</p>',
  logo: 'logo3.png'} 
- {avatar: 'face-atariboy.jpg',
  name: 'Aristotle',
  title: 'Greek Philosopher',
  quote: '<p><strong>We are what we repeatedly do.</strong> Excellence, then, is not an act, but a habit.</p>',
  logo:  'logo2.png'}  
- {avatar: 'face-teleject.jpg',
  name: 'Swami Satchidananda',
  title: 'The Yoga Sutras',
  quote: '<p><strong>If you do not pour water on your plant, what will happen?</strong> It will slowly wither and die. Our habits will also slowly wither and die away if we do not give them an opportunity to manifest. You need not fight to stop a habit. Just don’t give it an opportunity to repeat itself.</p>',
  logo: 'logo4.png'}   

#-------------------------------
# Contact Section

social:

- {icon: 'linkedin', link: 'https://www.linkedin.com/in/teckmon-siaw-83b9303a'}
- {icon: 'instagram', link: 'http://instagram.com/teckmonster'}
- {icon: 'pinterest', link: 'https://pinterest.com/petiteweightlifter'}
- {icon: 'youtube', link: 'https://www.youtube.com/petiteweightlifter'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
